version: '3.7'

services:
  scholar-utilities:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
      target: production
  tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
      target: tests